/**
 * AGENTS.md Generator (Linux Foundation AAIF standard)
 * @see https://agents.md
 */

import { existsSync, writeFileSync } from 'fs';
import { join } from 'path';
import { getProjectName, formatTechStack } from './base.js';

/**
 * Generate AGENTS.md file (Linux Foundation AAIF standard).
 *
 * Creates a standardized AGENTS.md file for AI agent interoperability,
 * based on project context from CLAUDE.md.
 *
 * @param {string} cwd - Current working directory
 * @param {Object|null} context - Project context parsed from CLAUDE.md
 * @param {Object} options - Generation options
 * @param {boolean} [options.force=false] - Overwrite existing files
 * @param {boolean} [options.dryRun=false] - Preview without writing files
 * @param {Object} results - Results accumulator object
 * @param {string[]} results.created - Array to push created file paths
 * @param {string[]} results.skipped - Array to push skipped file paths
 * @returns {Promise<void>} Resolves when generation is complete
 * @see https://agents.md - AAIF standard specification
 */
export async function generateAgentsMd(cwd, context, options, results) {
  const targetPath = join(cwd, 'AGENTS.md');

  if (existsSync(targetPath) && !options.force) {
    results.skipped.push('AGENTS.md (already exists, use --force)');
    return;
  }

  const content = generateAgentsMdContent(context);

  if (!options.dryRun) {
    writeFileSync(targetPath, content);
  }
  results.created.push('AGENTS.md');
}

/**
 * Generate AGENTS.md content
 * @param {object|null} context - Project context
 * @returns {string} Generated content
 */
export function generateAgentsMdContent(context) {
  const projectName = getProjectName(context);
  const techStackStr = formatTechStack(context);

  return `# AGENTS.md

> Configuration for AI coding agents.
> Part of the [AAIF (Agentic AI Foundation)](https://aaif.io) standard under Linux Foundation governance.
> See [agents.md](https://agents.md) for specification.

## Project Overview

**Name**: ${projectName}
**Stack**: ${techStackStr}

${context?.overview || 'A software project configured for AI-assisted development.'}

## Build & Test

\`\`\`bash
# Install dependencies
npm install

# Run tests
npm test

# Build project
npm run build

# Run linter
npm run lint
\`\`\`

${context?.commands || ''}

## Architecture Overview

${
  context?.architecture ||
  `This project follows standard practices for its technology stack.

Key directories:
- \`src/\` - Source code
- \`tests/\` - Test files
- \`docs/\` - Documentation`
}

## Code Style & Conventions

${
  context?.conventions ||
  `- Use consistent naming conventions
- Follow the existing code style in the repository
- Write meaningful commit messages using conventional commits
- Add tests for new functionality`
}

## Security Guidelines

When generating or modifying code:

${
  context?.securityChecklist?.length > 0
    ? context.securityChecklist.map(item => `- ${item}`).join('\n')
    : `- Never hardcode secrets or credentials
- Validate all user inputs
- Avoid SQL/command/XSS injection vulnerabilities
- Verify dependencies exist before adding them
- Handle errors without exposing internal details`
}

## Git Workflow

- Create feature branches from \`main\`
- Use conventional commit messages (feat, fix, docs, refactor, test)
- Run tests before committing
- Request review for significant changes

## Boundaries & Restrictions

### Files to NEVER modify without explicit permission:
- \`.env\` files (contain secrets)
- \`package-lock.json\` / \`yarn.lock\` (modify via package manager)
- Generated files in \`dist/\` or \`build/\`
- Migration files (create new ones instead)

### Patterns to follow:
- Match existing code style
- Prefer composition over inheritance
- Keep functions focused and small
- Document complex logic

## Verification Commands

Before completing any task, run these checks:

\`\`\`bash
# Type checking (if applicable)
npm run typecheck || true

# Linting
npm run lint

# Tests
npm test

# Build verification
npm run build
\`\`\`

---
*Generated by [AI Excellence Framework](https://github.com/ai-excellence-framework/ai-excellence-framework)*
`;
}
